Repository GlowTales/GlowTales-Client, pull requests merged in 2024-08, with the labels that each got.

#3 chore : 나눔스퀘어라운드 글꼴 global style로 적용
  index.html
  src/App.tsx
  src/styles/fonts/NanumSquareRound.css
  src/styles/fonts/NanumSqueareRound/NanumSquareRoundB.ttf
  src/styles/fonts/NanumSqueareRound/NanumSquareRoundB.woff
  src/styles/fonts/NanumSqueareRound/NanumSquareRoundB.woff2
  src/styles/fonts/NanumSqueareRound/NanumSquareRoundEB.ttf
  src/styles/fonts/NanumSqueareRound/NanumSquareRoundEB.woff
  src/styles/fonts/NanumSqueareRound/NanumSquareRoundEB.woff2
  src/styles/fonts/NanumSqueareRound/NanumSquareRoundL.ttf
  src/styles/fonts/NanumSqueareRound/NanumSquareRoundL.woff
  src/styles/fonts/NanumSqueareRound/NanumSquareRoundL.woff2
  src/styles/fonts/NanumSqueareRound/NanumSquareRoundR.ttf
  src/styles/fonts/NanumSqueareRound/NanumSquareRoundR.woff
  src/styles/fonts/NanumSqueareRound/NanumSquareRoundR.woff2
  src/styles/global.css
Labels: FEAT

#4 feat: 스플래시 스크린, 로그인 페이지 퍼블리싱
  index.html
  public/loginBubble.png
  public/loginbtn.png
  public/logo.svg
  public/mainLogo.svg
  public/vite.svg
  src/components/common/common.styled.ts
  src/components/login/Login.styled.ts
  src/components/login/Login.tsx
  src/components/splash/Splash.tsx
  src/pages/Login.tsx
  src/pages/LoginPage.tsx
  src/pages/LogoMain.tsx
  src/pages/Onboarding.tsx
  src/pages/OnboardingPage.tsx
  src/pages/SplashScreen.tsx
  src/router.tsx
  src/styles/global.css
  tsconfig.app.json
  tsconfig.node.json
  vite.config.ts
Labels: FEAT

#9 feat : 카카오 로그인 클라이언트 파트 완료
  public/logo.png
  public/logo.webp
  src/components/common/LoadingSpinner.tsx
  src/components/common/Spinner.tsx
  src/components/common/common.styled.ts
  src/components/login/Login.tsx
  src/components/login/kakaoLoginConfig.ts
  src/pages/KakaoRedirect.tsx
  src/router.tsx
  vite-env.d.ts
Labels: FEAT

#10 [FEAT] Dropdown 공통 컴포넌트 구현
  public/america.png
  public/china.png
  public/dropdowntri.png
  public/japan.png
  public/korea.png
  src/components/common/Dropdown.styled.ts
  src/components/common/Dropdown.tsx
  src/pages/OnboardingPage.tsx
  src/type/dropdown.d.ts
  src/types/test.tsx
  tsconfig.json
  vite.config.ts
Labels: FEAT

#15 feat: 로그인 api 연결
  src/apis/login.ts
  src/apis/test.tsx
  src/pages/KakaoRedirect.tsx
  src/utils/localStorage.ts
  tsconfig.json
  vite.config.ts
Labels: FEAT

#18 [FEAT] Storybook 설치 및 컴포넌트 테스트 추가 & 지속적 배포 적용
  .eslintrc.json
  .github/workflows/chromatic.yml
  .gitignore
  .storybook/main.ts
  .storybook/preview.ts
  package-lock.json
  package.json
  src/pages/OnboardingPage.tsx
  src/stories/Dropdown.stories.ts
  src/stories/Introduction.mdx
  src/stories/assets/github.svg
Labels: FEAT

#20 [FEAT] 동화 생성 키워드 선택 페이지 퍼블리싱
  src/components/common/NextBtn.tsx
  src/components/selectKeyword/SelectKeyword.styeld.ts
  src/components/selectKeyword/SelectKeyword.tsx
  src/components/selectKeyword/data.json
  src/pages/OnboardingPage.tsx
  src/pages/SelectKeywordPage.tsx
  src/router.tsx
Labels: FEAT

#22 [FEAT] 카카오 로그인 연결 완료
  src/apis/authAxois.ts
  src/apis/createTales.ts
  src/apis/login.ts
  src/components/tales/createMain/SelectOption/InputImg.tsx
  src/main.tsx
  src/pages/KakaoRedirect.tsx
  src/type/login.d.ts
Labels: FEAT

#31 [FEAT] 온보딩 퍼블리싱 및 동작 구현
  public/correct.png
  public/learningFinish.png
  public/onboardingFinish.png
  public/wrong.png
  src/components/common/FinishScreen.tsx
  src/components/common/NextBtn.tsx
  src/components/common/progressBar/ProgressBar.styeld.ts
  src/components/common/progressBar/ProgressBar.tsx
  src/components/common/selectOption/SelectBtn.tsx
  src/components/common/selectOption/SelectOptionList.styled.ts
  src/components/common/selectOption/SelectOptionList.tsx
  src/components/login/Login.tsx
  src/components/onboarding/AgeInput.tsx
  src/components/onboarding/SelectAge.tsx
  src/components/onboarding/SelectLanguage.tsx
  src/components/onboarding/SelectLevel.tsx
  src/components/onboarding/onboarding.styled.ts
  src/components/tales/readTale/ReadTale.tsx
  src/components/tales/taleDetail/TaleDetail.tsx
  src/hooks/test.tsx
  src/hooks/useAgeInput.ts
  src/hooks/useOnboarding.ts
  src/hooks/useResult.ts
  src/hooks/useSelectLevel.ts
  src/pages/OnboardingPage.tsx
  src/stories/Dropdown.stories.ts
  src/type/selectList.d.ts
  src/utils/defaultData.ts
  tsconfig.json
  vite.config.ts
Labels: FEAT

#32 [FEAT] 온보딩 api 연결 및 로그인 라우팅 수정
  public/loginGraphic.png
  src/apis/login.ts
  src/components/common/FinishScreen.tsx
  src/components/login/Login.styled.ts
  src/components/login/Login.tsx
  src/hooks/useOnboarding.ts
  src/pages/KakaoRedirect.tsx
  src/pages/OnboardingPage.tsx
Labels: FEAT

#34 [FEAT] 동화 생성 api 연결 및 동화 출력
  src/apis/authAxois.ts
  src/apis/createTales.ts
  src/components/tales/createMain/SelectOption/SelectOption.tsx
  src/components/tales/createTale/CreateTale.styled.ts
  src/components/tales/createTale/CreateTale.tsx
  src/components/tales/readTale/ReadTale.styled.ts
  src/components/tales/readTale/ReadTale.tsx
  src/components/tales/taleDetail/TaleDetail.styled.ts
  src/components/tales/taleDetail/TaleDetail.tsx
  src/pages/CreateMainPage.tsx
  src/pages/CreateTalePage.tsx
  src/pages/ReadTalePage.tsx
  src/router.tsx
  src/type/createTale.d.ts
  src/utils/defaultData.ts
Labels: FEAT

#35 [FEAT] 핵심 퀴즈 읽어주기, 객관식, 주관식 부분 퍼블리싱 및 동작 구현
  package-lock.json
  package.json
  public/speaker.png
  src/apis/home.ts
  src/apis/learning.ts
  src/components/common/NextBtn.tsx
  src/components/learn/ChoiceQuiz.tsx
  src/components/learn/EssayQuiz.tsx
  src/components/learn/LearnTaleKeys.tsx
  src/components/learn/SentenceQuiz.tsx
  src/components/learn/SpeakPractice.tsx
  src/components/learn/TaleLearn.tsx
  src/components/learn/learn.styled.ts
  src/hooks/useLearning.ts
  src/pages/HomePage.tsx
  src/pages/TaleLearnPage.tsx
  src/router.tsx
  src/type/learning.d.ts
  src/type/selectList.d.ts
Labels: FEAT

#38 [FEAT] 학습하기 API 연결 및 기능 구현 완료
  src/apis/authAxois.ts
  src/apis/learning.ts
  src/components/common/NextBtn.tsx
  src/components/common/common.styled.ts
  src/components/common/selectOption/SelectOptionList.tsx
  src/components/common/tabBar/TabBar.styled.ts
  src/components/common/tabBar/TabBar.tsx
  src/components/learn/ChoiceQuiz.tsx
  src/components/learn/EssayQuiz.tsx
  src/components/learn/SentenceQuiz.tsx
  src/components/learn/SpeakPractice.tsx
  src/components/learn/TaleLearn.tsx
  src/components/learn/learn.styled.ts
  src/components/tales/selectKeyword/SelectKeyword.styeld.ts
  src/components/tales/selectKeyword/SelectKeyword.tsx
  src/hooks/useLearning.ts
  src/pages/TaleLearnPage.tsx
  src/type/learning.d.ts
  src/utils/PrivateRoute.tsx
  src/utils/constants/QuizStage.ts
Labels: FEAT

#40 [FEAT] 문장 음성 읽기 기능 구현
  src/components/tales/readTale/ReadTale.tsx
  src/utils/speechUtil.ts
Labels: FEAT

#43 [FEAT] 홈페이지 퍼블리싱
  public/fullLogo.png
  public/statusImg.png
  src/components/home/Home.styled.ts
  src/components/home/Home.tsx
  src/components/home/homeHeader/HomeHeader.styled.ts
  src/components/home/homeHeader/HomeHeader.tsx
  src/components/home/homeRecentTales/Card.styled.ts
  src/components/home/homeRecentTales/Card.tsx
  src/components/home/homeRecentTales/HomeRecentTales.styled.ts
  src/components/home/homeRecentTales/HomeRecentTales.tsx
  src/components/home/homeStatus/HomeStatus.styled.ts
  src/components/home/homeStatus/HomeStatus.tsx
  src/components/tales/readTale/ReadTale.tsx
  src/pages/HomePage.tsx
  src/type/createTale.d.ts
  src/utils/defaultData.ts
  src/utils/speechUtil.ts
Labels: FEAT

#42 [FEAT] 퀴즈 만들기 퍼블리싱 및 동작 구현
  src/apis/learning.ts
  src/components/common/spinner/LoadingScreen.tsx
  src/components/learn/CreateQuiz.tsx
  src/components/learn/PreLearningQuestion.tsx
  src/components/learn/SentenceQuiz.tsx
  src/components/learn/learn.styled.ts
  src/components/tales/readTale/ReadTale.tsx
  src/pages/PreLearningQuestionPage.tsx
  src/router.tsx
Labels: FEAT

#44 [FEAT] 핵심 단어, 문장 연습 API 연결
  src/apis/learning.ts
  src/components/common/FinishScreen.tsx
  src/components/common/common.styled.ts
  src/components/common/dropDown/Dropdown.styled.ts
  src/components/common/dropDown/Dropdown.tsx
  src/components/common/progressBar/ProgressBar.styeld.ts
  src/components/learn/ChoiceQuiz.tsx
  src/components/learn/CreateQuiz.tsx
  src/components/learn/EssayQuiz.tsx
  src/components/learn/LearnTaleKeys.tsx
  src/components/learn/PreLearningQuestion.tsx
  src/components/learn/SentenceQuiz.tsx
  src/components/learn/SpeakPractice.tsx
  src/components/learn/TaleLearn.tsx
  src/components/learn/learn.styled.ts
  src/components/learn/speakPractice.styled.ts
  src/components/onboarding/AgeInput.tsx
  src/components/onboarding/Onboarding.tsx
  src/components/tales/readTale/ReadTale.tsx
  src/hooks/useLearning.ts
  src/hooks/useOnboarding.ts
  src/pages/OnboardingPage.tsx
  src/pages/TaleLearnPage.tsx
  src/styles/global.css
  src/type/learning.d.ts
  src/utils/constants/QuizStage.ts
  src/utils/defaultData.ts
  src/utils/learnUtil.ts
  src/utils/speechUtil.ts
Labels: FEAT

#46 [FEAT] 홈 컴포넌트 수정 및 필요 api 확인
  public/shelf.png
  public/taleGraphic1.png
  public/taleGraphic2.png
  public/taleGraphic3.png
  public/taleGraphic4.png
  src/apis/createTales.ts
  src/apis/login.ts
  src/components/common/modal/Modal.styled.ts
  src/components/common/modal/Modal.tsx
  src/components/home/Home.styled.ts
  src/components/home/Home.tsx
  src/components/home/homeRecentTales/Card.styled.ts
  src/components/home/homeRecentTales/Card.tsx
  src/components/home/homeRecentTales/HomeRecentTales.styled.ts
  src/components/home/homeRecentTales/HomeRecentTales.tsx
  src/type/card.d.ts
  src/type/createTale.d.ts
Labels: FEAT

#49 [FEAT] 최근 생성 동화 API 연결 및 더보기 구현
  src/apis/createTales.ts
  src/components/home/Home.styled.ts
  src/components/home/homeRecentTales/Card.tsx
  src/components/home/homeRecentTales/HomeRecentTales.styled.ts
  src/components/home/homeRecentTales/HomeRecentTales.tsx
  src/components/home/homeRecentTales/MoreRecentTales.tsx
  src/components/home/homeStatus/HomeStatus.tsx
  src/components/tales/createMain/CreateMain.styled.ts
  src/components/tales/readTale/ReadTale.tsx
  src/router.tsx
  src/styles/global.css
  src/type/card.d.ts
  src/utils/defaultData.ts
Labels: FEAT

#50 feat: home 컴포넌트 반응형 구현
  package-lock.json
  package.json
  src/components/home/homeRecentTales/HomeRecentTales.styled.ts
  src/components/home/homeRecentTales/HomeRecentTales.tsx
Labels: FEAT

#51 [FEAT] home 스타일 코드 분리 및 Learn 페이지 구현 준비
  src/components/common/common.styled.ts
  src/components/home/homeRecentTales/Card.styled.ts
  src/components/home/homeRecentTales/HomeRecentTales.styled.ts
  src/components/home/homeRecentTales/HomeRecentTales.tsx
  src/components/home/homeRecentTales/MoreRecentTales.tsx
  src/components/learn/learnMain/Learn.styeld.ts
  src/components/learn/learnMain/Learn.tsx
  src/pages/LearningPage.tsx
Labels: FEAT

#53 [FEAT] 학습하기 메인 탭 구현
  src/apis/createTales.ts
  src/apis/home.ts
  src/components/common/common.styled.ts
  src/components/home/homeRecentTales/Card.styled.ts
  src/components/home/homeRecentTales/Card.tsx
  src/components/home/homeRecentTales/HomeRecentTales.tsx
  src/components/home/homeRecentTales/MoreRecentTales.tsx
  src/components/learn/learnMain/Learn.tsx
  src/components/learn/learnMain/learned/Learned.tsx
  src/components/learn/learnMain/learned/LearnedMore.tsx
  src/components/learn/learnMain/unLearned/UnLearned.tsx
  src/components/learn/learnMain/unLearned/UnLearnedMore.tsx
  src/components/learn/learnMain/word/Word.styled.ts
  src/components/learn/learnMain/word/Word.tsx
  src/components/learn/learnMain/word/WordMore.tsx
  src/type/card.d.ts
Labels: FEAT

#54 Feat/#45
  src/apis/createTales.ts
  src/apis/home.ts
  src/components/common/common.styled.ts
  src/components/common/tabBar/TabBar.styled.ts
  src/components/common/tabBar/TabBar.tsx
  src/components/home/homeRecentTales/HomeRecentTales.styled.ts
  src/components/home/homeRecentTales/HomeRecentTales.tsx
  src/components/home/homeRecentTales/MoreRecentTales.tsx
  src/components/home/homeStatus/HomeStatus.styled.ts
  src/components/home/homeStatus/HomeStatus.tsx
  src/components/learn/learnMain/Learn.tsx
  src/components/learn/learnMain/learned/Learned.tsx
  src/components/learn/learnMain/learned/LearnedMore.tsx
  src/components/learn/learnMain/unLearned/UnLearned.tsx
  src/components/learn/learnMain/unLearned/UnLearnedMore.tsx
  src/components/learn/learnMain/word/Word.styled.ts
  src/components/learn/learnMain/word/Word.tsx
  src/components/learn/learnMain/word/WordMore.tsx
  src/components/tales/createMain/CreateMain.styled.ts
  src/router.tsx
  src/type/login.d.ts
Labels: FEAT

#55 [FEAT] 메인 api 연결 및 카드 구조 변경
  src/Layout.tsx
  src/components/common/card/Card.styled.ts
  src/components/common/card/Card.tsx
  src/components/common/common.styled.ts
  src/components/learn/TaleLearn.tsx
  src/components/learn/pre/CreateQuiz.tsx
  src/components/learn/pre/PreLearningQuestion.tsx
  src/components/learn/quiz/ChoiceQuiz.tsx
  src/components/learn/quiz/EssayQuiz.tsx
  src/components/learn/quiz/SentenceQuiz.tsx
  src/components/learn/quiz/SpeakPractice.tsx
  src/components/login/Login.tsx
  src/components/main/homeMain/Home.styled.ts
  src/components/main/homeMain/Home.tsx
  src/components/main/homeMain/homeHeader/HomeHeader.styled.ts
  src/components/main/homeMain/homeHeader/HomeHeader.tsx
  src/components/main/homeMain/homeRecentTales/HomeRecentTales.styled.ts
  src/components/main/homeMain/homeRecentTales/HomeRecentTales.tsx
  src/components/main/homeMain/homeRecentTales/MoreRecentTales.tsx
  src/components/main/homeMain/homeStatus/HomeStatus.styled.ts
  src/components/main/homeMain/homeStatus/HomeStatus.tsx
  src/components/main/learnMain/Learn.tsx
  src/components/main/learnMain/learned/Learned.tsx
  src/components/main/learnMain/learned/LearnedMore.tsx
  src/components/main/learnMain/unLearned/UnLearned.tsx
  src/components/main/learnMain/unLearned/UnLearnedMore.tsx
  src/components/main/learnMain/word/Word.styled.ts
  src/components/main/learnMain/word/Word.tsx
  src/components/main/learnMain/word/WordMore.tsx
  src/components/tales/readTale/ReadTale.styled.ts
  src/components/tales/readTale/ReadTale.tsx
  src/pages/HomePage.tsx
  src/pages/LearningPage.tsx
  src/pages/PreLearningQuestionPage.tsx
  src/pages/TaleLearnPage.tsx
  src/router.tsx
  src/styles/global.css
  src/type/card.d.ts
  src/type/createTale.d.ts
  src/utils/ScrollToTop.tsx
Labels: FEAT, STYLE

#58 [FEAT] 모달창 구현
  src/components/common/modal/Modal.styled.ts
  src/components/common/modal/Modal.tsx
  src/components/common/spinner/LoadingScreen.tsx
  src/components/learn/TaleLearn.tsx
  src/components/learn/pre/PreLearningQuestion.tsx
  src/components/tales/createTale/CreateTale.tsx
  src/components/tales/readTale/ReadTale.tsx
  src/components/tales/selectKeyword/SelectKeyword.tsx
  src/components/tales/taleDetail/TaleDetail.tsx
  src/hooks/useNavigationWarning.ts
  src/type/modal.d.ts
Labels: FEAT

#60 [REFACTOR] taleDetail 컴포넌트 리팩토링
  public/topGraphic.png
  src/components/common/header/Header.tsx
  src/components/common/spinner/LoadingScreen.tsx
  src/components/learn/TaleLearn.tsx
  src/components/learn/learn.styled.ts
  src/components/learn/pre/PreLearningQuestion.tsx
  src/components/main/homeMain/homeRecentTales/MoreRecentTales.tsx
  src/components/main/learnMain/learned/LearnedMore.tsx
  src/components/main/learnMain/unLearned/UnLearnedMore.tsx
  src/components/main/learnMain/word/WordMore.tsx
  src/components/tales/createMain/SelectOption/InputImg.tsx
  src/components/tales/createTale/CreateTale.tsx
  src/components/tales/readTale/ReadTale.styled.ts
  src/components/tales/readTale/ReadTale.tsx
  src/components/tales/selectKeyword/SelectKeyword.tsx
  src/components/tales/selectKeyword/data.json
  src/components/tales/taleDetail/TaleDetail.styled.ts
  src/components/tales/taleDetail/TaleDetail.tsx
  src/hooks/taleDetail/useCharacters.ts
  src/hooks/taleDetail/useContents.ts
  src/hooks/taleDetail/useElementState.ts
  src/hooks/taleDetail/useMood.ts
  src/hooks/taleDetail/useTaleDetail.ts
  src/styles/global.css
  src/type/header.d.ts
  src/utils/defaultData.ts
  src/utils/getRandom.ts
Labels: FEAT, FIX, REFACTOR

#61 [CHORE] 스토리북 파일 확장자명 변경 및 불필요한 코드 제거
  README.md
  package.json
  src/apis/authAxois.ts
  src/apis/createTales.ts
  src/apis/settings.ts
  src/assets/react.svg
  src/components/learn/TaleLearn.tsx
  src/components/main/homeMain/homeRecentTales/HomeRecentTales.tsx
  src/pages/TaleLearnPage.tsx
  src/stories/Dropdown.stories.tsx
  src/stories/ProgressBar.stories.tsx
  src/stories/SelectOptionList.stories.tsx
  src/type/card.d.ts
  src/type/dropdown.d.ts
Labels: CHORE, FIX

#63 [FIX] 오타 수정
  src/components/main/homeMain/homeStatus/HomeStatus.tsx
Labels: FIX

#65 [FEAT] PWA 설치 및 적용
  index.html
  package-lock.json
  package.json
  public/apple-touch-icon-180x180.png
  public/favicon.ico
  public/maskable-icon-512x512.png
  public/pwa-192x192.png
  public/pwa-512x512.png
  public/pwa-64x64.png
  public/pwaIcon.svg
  vite.config.ts
Labels: FEAT
